apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: maximo-ai-agent-data
  namespace: maximo-ai-agent
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: managed-nfs-storage
